# Generated by Django 5.2.4 on 2025-07-14 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('preferred_wake_time', models.TimeField(blank=True, null=True)),
                ('preferred_sleep_time', models.TimeField(blank=True, null=True)),
                ('default_deep_work_duration', models.IntegerField(default=120)),
                ('preferred_break_duration', models.IntegerField(default=15)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('daily_motivation_enabled', models.BooleanField(default=True)),
                ('motivation_time', models.TimeField(blank=True, null=True)),
                ('emergency_motivation_keywords', models.JSONField(default=list)),
                ('support_network_enabled', models.BooleanField(default=True)),
                ('emergency_contact_threshold', models.IntegerField(default=2)),
                ('energy_tracking_enabled', models.BooleanField(default=True)),
                ('energy_reminder_frequency', models.IntegerField(default=4)),
                ('anonymous_progress_sharing', models.BooleanField(default=False)),
                ('public_achievements', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monk_mode_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
